services:

  stub1:
    build: .
    image: stub_image
    container_name: stub1
    networks:
      - stubs_network
    hostname: stub1

  balancer:
    image: nginx:latest
    depends_on:
      - stub1
      - stub2
      - stub3
      - stub4
    ports:
      - "80:80" # map internal port 80 to external port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # use custom nginx config
    networks:
      - stubs_network
      - external_network


networks:
  stubs_network:
  external_network:
    driver: bridge