services:

  stub1:
    build: .
    image: stub_image
    container_name: stub1
    hostname: stub1
    networks:
      - stubs_network

  stub2:
    image: stub_image
    container_name: stub2
    depends_on:
      - stub1
    pull_policy: never
    networks:
      - stubs_network
    hostname: stub2

  balancer:
    image: nginx:latest
    depends_on:
      - stub1
      - stub2
    ports:
      - "80:80" # map internal port 80 to external port 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # use custom nginx config
    hostname: nginx-balancer
    networks:
      - stubs_network
      - external_network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - influxdb
    ports:
      - '3000:3000'  # Expose Grafana on port 3000
    volumes:
      - grafana_data:/var/lib/grafana  # Mount the Grafana data directory
    hostname: grafana
    networks:
      - external_network


  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'  # Expose InfluxDB on port 8086
    volumes:
      - influxdb_data:/var/lib/influxdb  # Mount the InfluxDB data directory
    hostname: influxdb
    networks:
      - external_network

volumes:
  grafana_data: {}  # Volume for Grafana data
  influxdb_data: {}  # Volume for InfluxDB data

networks:
  stubs_network:
  external_network:
    driver: bridge