{
 "title": "1",
 "description": "1",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Services: RPS on each",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=\"/hello\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Services: RPS summary",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri=\"/hello\"}[1m]))",
     "legendFormat": "Summ RPS"
    }
   ]
  },
  {
   "title": "Jmeter active threads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "jmeter_active_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jmeter: Success responces",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "rate(jmeter_response_time_histogram_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}